add grunt clean:coverage task
If we don’t clean the coverage directory, we can get errors like this:

    Running "coverage" task
    Fatal error: Cannot read property 'length' of undefined

This is due to coverage reports being out of sync, as described in this
issue against the grunt-istanbul-coverage project:
https://github.com/daniellmb/grunt-istanbul-coverage/issues/10